### ISSUE TITLE
Textures for pre-1.5 animated blocks and items

### ISSUE THREAD

**Issue by muzikbike** [NeRdTheNed/MC-TextureGen#1]
- Still water: Documented [here.](https://github.com/UnknownShadow200/ClassiCube/wiki/MInecraft-Classic-lava-animation-algorithm) Don't know of any changes that happened to it between 0.0.19a and 13w01b (unless you count swamp tinting), so I'm assuming it stayed the same.
- Still lava: Again documented [here.](https://github.com/UnknownShadow200/ClassiCube/wiki/MInecraft-Classic-lava-animation-algorithm) Also don't think this changed at all between 0.0.19a and 13w01b.
- Flowing water: Not too sure how this was generated, although probably very similar to still water. The texture seems to have been first added in the first indev version, for the sides of water blocks, although it appeared to be still without any translational effects to imply motion. This translation was first added in the June 15th infdev build. I am not aware of any other changes.
- Flowing lava: Probably first introduced in the 0616 build, this is identical to the still lava of the time but had the translation effect. Again, not aware of any other changes.
- Fire: Not sure how this was generated. Worth noting is that in the current (1.5 and up) versions of the game there are two fire textures, which are visually similar but still different, seemingly used to make fire appear more random. The existence of two different fire placeholder textures in terrain.png since Beta 1.2 implies this was also the case this far back as well (and may have been even before that, although I can't be sure).
- Nether portals: Again not sure how this was generated. Documentation as to how this, fire and flowing water were generated would be useful.
- Gears: Again there were two instances, one for each direction of rotation. These without a doubt used the misc/gearmiddle.png remaining stationary, and rotated misc/gear.png around it, pixelated to appear 16x16 at all times.
- Clocks: These used the clock file from terrain.png, with the purple section replaced with a rotated and pixelated dial.png. Clocks were far more precise with these textures than what they were changed to in 1.5 and up.
- Compasses: A similar story, although the needle appears to be automatically generated and not based on any texture. Again much more precise than 1.5's replacement.

I do not know how animated textures for all of these were generated in early Pocket Edition or Console Edition where applicable, although I'd assume mostly the same (possibly with subtle hardware differences perhaps due to using a different RNG or the like).

**Comment by NeRdTheNed** [comment]
> * Still water: Documented [here.](https://github.com/UnknownShadow200/ClassiCube/wiki/MInecraft-Classic-lava-animation-algorithm) Don't know of any changes that happened to it between 0.0.19a and 13w01b (unless you count swamp tinting), so I'm assuming it stayed the same.
> * Still lava: Again documented [here.](https://github.com/UnknownShadow200/ClassiCube/wiki/MInecraft-Classic-lava-animation-algorithm) Also don't think this changed at all between 0.0.19a and 13w01b.
> * Flowing water: Not too sure how this was generated, although probably very similar to still water. The texture seems to have been first added in the first indev version, for the sides of water blocks, although it appeared to be still without any translational effects to imply motion. This translation was first added in the June 15th infdev build. I am not aware of any other changes.
> * Flowing lava: Probably first introduced in the 0616 build, this is identical to the still lava of the time but had the translation effect. Again, not aware of any other changes.
> * Fire: Not sure how this was generated. Worth noting is that in the current (1.5 and up) versions of the game there are two fire textures, which are visually similar but still different, seemingly used to make fire appear more random. The existence of two different fire placeholder textures in terrain.png since Beta 1.2 implies this was also the case this far back as well (and may have been even before that, although I can't be sure).
> * Nether portals: Again not sure how this was generated. Documentation as to how this, fire and flowing water were generated would be useful.
> * Gears: Again there were two instances, one for each direction of rotation. These without a doubt used the misc/gearmiddle.png remaining stationary, and rotated misc/gear.png around it, pixelated to appear 16x16 at all times.
> * Clocks: These used the clock file from terrain.png, with the purple section replaced with a rotated and pixelated dial.png. Clocks were far more precise with these textures than what they were changed to in 1.5 and up.
> * Compasses: A similar story, although the needle appears to be automatically generated and not based on any texture. Again much more precise than 1.5's replacement.
> 
> I do not know how animated textures for all of these were generated in early Pocket Edition or Console Edition where applicable, although I'd assume mostly the same (possibly with subtle hardware differences perhaps due to using a different RNG or the like).

@muzikbike Wow, this is a large amount of very useful information, thanks for posting it here! I'll try to work my way through implementing some of these. Sorry for not responding until now, GitHub doesn't seem to notify me when someone makes an issue on a project.

**Comment by muzikbike** [comment]
There is now a wiki page, which also includes nether portal details: https://minecraft.fandom.com/wiki/Procedural_animated_texture_generation

**Comment by muzikbike** [comment]
It also seems that lava was different around c0.0.19a, but finding out how that works will probably require some reverse engineering.

**Comment by NeRdTheNed** [comment]
@muzikbike The gear rotation animation has been added to [the latest release](https://github.com/NeRdTheNed/MC-TextureGen/releases/tag/v1.2.0)! It'll take a while to work through the entire collection of procedurally generated textures, but I'll try to keep you updated.

**Comment by muzikbike** [comment]
Should I split this ticket into one per animated texture?

**Comment by NeRdTheNed** [comment]
> Should I split this ticket into one per animated texture?

@muzikbike That would probably be easier to manage, so I'd be happy for you to do it! By the way, I just implemented nether portal texture generation, so you won't need a new ticket for it!

**Comment by muzikbike** [comment]
Now split fully into 10 separate cases.
