### ISSUE TITLE
(in-20100109 - 13w01b) Fire 0

### ISSUE THREAD

**Issue by muzikbike** [NeRdTheNed/MC-TextureGen#2]
I've done some searching, but was ultimately unable to find any documentation of the auto-generated fire texture online. However, this Reddit post is by someone who has looked at it before, and may be worth contacting: https://www.reddit.com/r/Minecraft/comments/m918dn/i_got_minecrafts_old_dynamic_texture_code_and/

![fireoldest](https://user-images.githubusercontent.com/52297970/128548203-05a4228c-2aca-4ec4-92fe-e18df29c3217.png)

As the fire texture very likely used RNG for generation, it may vary between sessions and getting a loopable animation may not be possible.

Worth noting is the fact that Java Edition used an LCG for random generation, whereas Pocket Edition used MT19937. Console Edition almost certainly also used LCG as its initial terrain generation was identical to Java Edition's. While both of these are intended for random number generation, and the results from changing them may not be distinguishable in normal situations, I'd recommend having two copies of the animation be generated, one per RNG type, as to have one texture generated for Java/Console and another for Pocket Edition.

**Comment by muzikbike** [comment]
![fireoldest](https://user-images.githubusercontent.com/52297970/128548203-05a4228c-2aca-4ec4-92fe-e18df29c3217.png)

**Comment by NeRdTheNed** [comment]
Mostly added in 90944f8e40db8b2a91ffc7e20845f924825be031, tracking any other unfinished business in #3.

**Comment by muzikbike** [comment]
The Pocket Edition case has been split into #27.
