### ISSUE TITLE
(13w38a-14w21b) Anisotropic Filtering 4x4 missing texture

### ISSUE THREAD

**Issue by muzikbike** [NeRdTheNed/MC-TextureGen#24]
This was originally tracked in #16.

Currently, MC-TextureGen generates the familiar 2x2 checkerboard missing texture, which appears to be the standard missing texture used in the 1.7 era. Indeed, this is the only version of the texture I can seem to get to appear in-game in this general version range. However, according to media created around this time period, there also appeared to be "higher-frequency" versions of this missing texture, featuring 16 squares instead of the usual 4.

For example, the following video clearly features an air item with this texture in 13w38b: https://www.youtube.com/watch?v=nJun57MSyYY

In addition, 1.8 introduces block models. During their introduction, the missing texture made several appearances. A notable bug report from the time includes multiple screenshots that appear to show this texture. https://bugs.mojang.com/browse/MC-47653
Some of the screenshots have an even higher-frequency checkerboard, implying there may be 8x8 or even higher versions of the texture. I'll have to check how the texture mapping on the missing model worked at the time, as to determine whether this is truly a section of an 8x8 texture, or just the 4x4 texture shrunk to fit a smaller square (thankfully the model wasn't procedurally generated at the time so this shouldn't be too hard to find out).

This file on the wiki https://minecraft.fandom.com/wiki/File:Missing_Texture_(frequency_2)_JE3.png was originally uploaded as the air item texture in 2020, which is considerably after these dates, which may or may not imply that it can still be reproduced.

The textures being higher frequency would imply that this version of the texture appears in HD texture packs, but most of the screenshots and videos appear to just use the default textures, and including some higher-resolution textures in a resource pack did not cause this texture to appear. As such, it may be hardware-dependent.

The fact that I cannot seem to find any records of this version of the texture after the roughly 1.6-1.8 time period may imply that it was removed in late 1.8 development, likely 14w25a, the version which merged the block and item texture atlases.

**Comment by muzikbike** [comment]
Three more tickets mentioning this 4x4 version of the texture, again all from the 14w10 era:
https://bugs.mojang.com/browse/MC-50238
https://bugs.mojang.com/browse/MC-50254
https://bugs.mojang.com/browse/MC-50266

**Comment by muzikbike** [comment]
Found it! This version of the texture is tied to the anisotropic filtering option. Having it disabled gives the usual 2x2 texture, but anything above that will give the 4x4 version instead. This disproves an 8x8 version of the texture, and also means we can get an exact version range - introduced in 13w38a, and removed in 14w25a.
![2021-10-13_08 35 56](https://user-images.githubusercontent.com/52297970/137088669-60f61097-9401-4f16-8401-5ba2b3d8630e.png)

**Comment by muzikbike** [comment]
To demonstrate how this texture is actually generated, I created a custom model to reveal larger sections of the atlas:
![](https://cdn.discordapp.com/attachments/399390463930400778/907812537561673728/2021-11-10_02.01.33.png)

Here it can be seen that this larger missing texture results from a 3x3 (probably any non-1 odd by odd) grid of said texture, and then taking the center 32x32 section from said region, as opposed to a 2x2 tiling of the original texture (even if the outcome is the same).

Hopefully generating this texture is simple enough now!

**Comment by NeRdTheNed** [comment]
Note for future research: my implementation is slightly different from how the texture is generated in game, but produces identical results as far as I know. I may re-implement this in a more faithful way in the future.
