### ISSUE TITLE
(0.0.19a - 13w01b) Still water

### ISSUE THREAD

**Issue by muzikbike** [NeRdTheNed/MC-TextureGen#4]
Still water's animation is documented here: https://github.com/UnknownShadow200/ClassiCube/wiki/MInecraft-Classic-lava-animation-algorithm

I am not aware if the still water texture changed at all between 0.0.19a and 13w01b. There is a chance it changed alongside lava in 0.0.22a, but I haven't seen any difference myself.

The still water texture was also used for the sides of water prior to the very start of Indev:

![vearlywater](https://user-images.githubusercontent.com/52297970/128548504-e1ae12a2-4269-4f47-b124-48fc0ae33370.png)
![earlywaterside](https://user-images.githubusercontent.com/52297970/128548488-61eb04b6-3a1a-40d5-b066-2f72bdc07b92.png)

As the still water texture used RNG for generation, it may vary between sessions and getting a loopable animation may not be possible.

Worth noting is the fact that Java Edition used an LCG for random generation, whereas Pocket Edition used MT19937. Console Edition almost certainly also used LCG as its initial terrain generation was identical to Java Edition's. While both of these are intended for random number generation, and the results from changing them may not be distinguishable in normal situations, I'd recommend having two copies of the animation be generated, one per RNG type, as to have one texture generated for Java/Console and another for Pocket Edition.

**Comment by NeRdTheNed** [comment]
Java version added in https://github.com/NeRdTheNed/MC-TextureGen/commit/e3c3859720c295601fc23fba5c348921a299a692. @muzikbike Should I close this issue, or should this stay open for console edition / pocket edition / other variants?

**Comment by muzikbike** [comment]
Feel free to close it, I might make a separate issue just for implementing a separate RNG to emulate pocket edition.

**Comment by muzikbike** [comment]
I assume this is still eligible for closing? Will do it if you don't in a few days

**Comment by NeRdTheNed** [comment]
> I assume this is still eligible for closing? Will do it if you don't in a few days

Sure, closing now!

**Comment by muzikbike** [comment]
The Pocket Edition case has been split into #25.
