### ISSUE TITLE
(0.0.19a - 0.0.21a_01) Still lava

### ISSUE THREAD

**Issue by muzikbike** [NeRdTheNed/MC-TextureGen#7]
This lava animation is notably different from the lava animation that came after - it appears much darker.

![firstlava](https://user-images.githubusercontent.com/52297970/128550166-888bb170-807f-4b95-b389-a9ba34e0d266.png)

I have found no documentation at all on this texture, so looking into the code of one of the versions that has it is probably required.

As the original still lava texture very likely used RNG for generation, it may vary between sessions and getting a loopable animation may not be possible.

**Comment by muzikbike** [comment]
Are you sure you meant to assign this still lava and not the other one?

**Comment by NeRdTheNed** [comment]
> Are you sure you meant to assign this still lava and not the other one?

I did, as I'm working on it right now! I'll also assign myself the other one, as they're almost identical.

**Comment by NeRdTheNed** [comment]
Added in https://github.com/NeRdTheNed/MC-TextureGen/commit/e3c3859720c295601fc23fba5c348921a299a692.
