### ISSUE TITLE
(0.0.22a - 13w01b) Still lava

### ISSUE THREAD

**Issue by muzikbike** [NeRdTheNed/MC-TextureGen#8]
This is the conventional lava animation, used for all sides of the lava block from 0.0.22a up until inf-20100615 and still for the top and bottom for inf-2010061601808 onwards. I am not aware of any changes made to this texture from 0.0.22a onwards. Documentation of this texture can be found here: https://github.com/UnknownShadow200/ClassiCube/wiki/MInecraft-Classic-lava-animation-algorithm

![secondlava](https://user-images.githubusercontent.com/52297970/128550472-31433da9-792c-4e92-8beb-db14c59183f8.png)

As the still lava texture used RNG for generation, it may vary between sessions and getting a loopable animation may not be possible.

Worth noting is the fact that Java Edition used an LCG for random generation, whereas Pocket Edition used MT19937. Console Edition almost certainly also used LCG as its initial terrain generation was identical to Java Edition's. While both of these are intended for random number generation, and the results from changing them may not be distinguishable in normal situations, I'd recommend having two copies of the animation be generated, one per RNG type, as to have one texture generated for Java/Console and another for Pocket Edition.

**Comment by NeRdTheNed** [comment]
Java version added in https://github.com/NeRdTheNed/MC-TextureGen/commit/e3c3859720c295601fc23fba5c348921a299a692. @muzikbike Should I close this issue, or should this stay open for console edition / pocket edition / other variants?

**Comment by muzikbike** [comment]
I assume this is still eligible for closing? Will do it if you don't in a few days

**Comment by NeRdTheNed** [comment]
> I assume this is still eligible for closing? Will do it if you don't in a few days

Sure, closing now!

**Comment by muzikbike** [comment]
The Pocket Edition case has been split into #26.
